SELECT D.NAME,
	E.SALARY,
	E.NAME
FROM PUBLIC.DEPARTMENTS AS D
JOIN
	(SELECT SALARY,
			NAME,
			DEPARTMENT_ID
		FROM
			(SELECT SALARY,
					NAME,
					DEPARTMENT_ID,
					ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) RN
				FROM PUBLIC.EMPLOYEES AS E) AS T
		WHERE T.RN = 1 ) AS E ON E.DEPARTMENT_ID = D.ID;