SELECT D.NAME
FROM PUBLIC.DEPARTMENTS D
JOIN
	(SELECT SUM(YEAR_BONUS * SALARY) AS S,
			DEPARTMENT_ID
		FROM PUBLIC.EMPLOYEES AS E
		GROUP BY DEPARTMENT_ID
		ORDER BY S DESC
		LIMIT 1) AS B ON D.ID = B.DEPARTMENT_ID