SELECT *,
	(END_SALARY_OLD / END_SALARY) AS SALARY_DIFF
FROM
	(SELECT D.NAME,
			D.SUPERVISOR,
			D.EMPLOYEE_COUNT,
			ROUND(AVG_WORK.WORK_YEARS_AVG,
				2) AS WORK_YEARS_AVG,
			ROUND(AVG_SALARY.SALARY_AVG,
				2) AS SALARY_AVG,
			JUN_COUNT.C AS JUN_COUNT,
			MID_COUNT.C AS MIDDLE_COUNT,
			SEN_COUNT.C AS SENIOR_COUNT,
			LED_COUNT.C AS LEAD_COUNT,
			SALARY_SUM.S AS SALARY_SUM,
			SALARY_OLD_SUM.S AS SALARY_OLD_SUM,
			SCORE_A_COUNT.C AS SCORE_A_COUNT,
			SCORE_B_COUNT.C AS SCORE_B_COUNT,
			SCORE_C_COUNT.C AS SCORE_C_COUNT,
			SCORE_D_COUNT.C AS SCORE_D_COUNT,
			SCORE_E_COUNT.C AS SCORE_E_COUNT,
			BONUS_COEF_AVG.A AS BONUS_COEF_AVG,
			BONUS.A AS BONUS,
			END_SALARY_OLD.A AS END_SALARY_OLD,
			END_SALARY.A AS END_SALARY
		FROM PUBLIC.DEPARTMENTS D
		LEFT JOIN
			(SELECT AVG((NOW()::date - EMPLOYED_DATE)::numeric / 365) AS WORK_YEARS_AVG,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS AVG_WORK ON D.ID = AVG_WORK.DEPARTMENT_ID
		LEFT JOIN
			(SELECT AVG(SALARY) AS SALARY_AVG,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS AVG_SALARY ON D.ID = AVG_SALARY.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(POSTION_LEVEL) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				WHERE POSTION_LEVEL = 'jun'
				GROUP BY DEPARTMENT_ID) AS JUN_COUNT ON D.ID = JUN_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(POSTION_LEVEL) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				WHERE POSTION_LEVEL = 'middle'
				GROUP BY DEPARTMENT_ID) AS MID_COUNT ON D.ID = MID_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(POSTION_LEVEL) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				WHERE POSTION_LEVEL = 'senior'
				GROUP BY DEPARTMENT_ID) AS SEN_COUNT ON D.ID = SEN_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(POSTION_LEVEL) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				WHERE POSTION_LEVEL = 'lead'
				GROUP BY DEPARTMENT_ID) AS LED_COUNT ON D.ID = LED_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT SUM(SALARY) AS S,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS SALARY_SUM ON D.ID = SALARY_SUM.DEPARTMENT_ID
		LEFT JOIN
			(SELECT SUM(SALARY_OLD) AS S,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS SALARY_OLD_SUM ON D.ID = SALARY_OLD_SUM.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(S.SCORE) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES E
				JOIN PUBLIC.SCORES S ON S.EMPLOYEE_ID = E.ID
				WHERE S.SCORE = 'A'
					AND date > NOW()::date - interval '1 Year'
				GROUP BY DEPARTMENT_ID) AS SCORE_A_COUNT ON D.ID = SCORE_A_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(S.SCORE) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES E
				JOIN PUBLIC.SCORES S ON S.EMPLOYEE_ID = E.ID
				WHERE S.SCORE = 'B'
					AND date > NOW()::date - interval '1 Year'
				GROUP BY DEPARTMENT_ID) AS SCORE_B_COUNT ON D.ID = SCORE_B_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(S.SCORE) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES E
				JOIN PUBLIC.SCORES S ON S.EMPLOYEE_ID = E.ID
				WHERE S.SCORE = 'C'
					AND date > NOW()::date - interval '1 Year'
				GROUP BY DEPARTMENT_ID) AS SCORE_C_COUNT ON D.ID = SCORE_C_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(S.SCORE) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES E
				JOIN PUBLIC.SCORES S ON S.EMPLOYEE_ID = E.ID
				WHERE S.SCORE = 'D'
					AND date > NOW()::date - interval '1 Year'
				GROUP BY DEPARTMENT_ID) AS SCORE_D_COUNT ON D.ID = SCORE_D_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT COUNT(S.SCORE) AS C,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES E
				JOIN PUBLIC.SCORES S ON S.EMPLOYEE_ID = E.ID
				WHERE S.SCORE = 'E'
					AND date > NOW()::date - interval '1 Year'
				GROUP BY DEPARTMENT_ID) AS SCORE_E_COUNT ON D.ID = SCORE_E_COUNT.DEPARTMENT_ID
		LEFT JOIN
			(SELECT AVG(YEAR_BONUS) AS A,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS BONUS_COEF_AVG ON D.ID = BONUS_COEF_AVG.DEPARTMENT_ID
		LEFT JOIN
			(SELECT SUM(YEAR_BONUS * SALARY) AS A,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS BONUS ON D.ID = BONUS.DEPARTMENT_ID
		LEFT JOIN
			(SELECT SUM((1 + YEAR_BONUS) * SALARY_OLD) AS A,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS END_SALARY_OLD ON D.ID = END_SALARY_OLD.DEPARTMENT_ID
		LEFT JOIN
			(SELECT SUM((1 + YEAR_BONUS) * SALARY) AS A,
					DEPARTMENT_ID
				FROM PUBLIC.EMPLOYEES
				GROUP BY DEPARTMENT_ID) AS END_SALARY ON D.ID = END_SALARY.DEPARTMENT_ID) AS T